server.port: 8083

spring:
  application.name: payment-service
  datasource:
    url: jdbc:mysql://127.0.0.1:33063/payment_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties.hibernate.format_sql: true